version: "3"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4567:4567"
    command: "bundle exec rerun --background 'ash bin/serve.sh'"
    privileged: true
    environment: 
      CHIRP_FILE_PATH: '/tmp/chirps.json'
